name: remote ssh command

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      id: ssh-step
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        #password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          date
          ls -a
          
    - name: Set result message
      id: result-message
      run: |
        if [[ "${{ steps.ssh-step.outcome }}" == "success" ]]; then
          echo "::set-output name=message::Başarılı! Dağıtıldı."
        else
          echo "::set-output name=message::SSH Action Result failed."
        fi

    - name: Send Email
      if: always() # Bu adımı her zaman çalıştırır.
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.HOST }}
        server_port: 587
        secure: false
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: GitHub Actions Result
        to: bolatoglu.onur@gmail.com
        from: ${{secrets.MAIL_USERNAME}} 
        ignore_cert: true
        body: ${{ steps.result-message.outputs.message }}
